server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 101.34.64.62
      port: 8501
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        prefer-ip-address: true

